Deneme4/Models/Computer.cs
    using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Deneme4.Models
{
    public class Computer
    {
        [Key]
        public int Pcid { get; set; }
        //[Required(ErrorMessage = "Type ur  Name")]
        //public string StudentName { get; set; }
        [Required(ErrorMessage = "Type ur Graphics Card's Name")]
        public string Graphicscard { get; set; }
        [Required(ErrorMessage = "Type ur Mainbord's Name ")]
        public string Mainboard { get; set; }
        [Required(ErrorMessage ="Type ur RAM's memory")]
        public string Ram { get; set; }
        [Required(ErrorMessage ="Type ur Monitor's Name")]
        public string Monitor { get; set; }

    }
}

Deneme4/Controllers/ComputerController.cs
using System;
using Deneme4.Models;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Deneme4.Resopsi;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Deneme4.Controllers
{
    public class ComputerController : Controller
    {
        Context c = new Context();
        ComputerReposi computerReposi = new ComputerReposi();
        public IActionResult CpIndex()
        {
            var data = c.computers.ToList();
            ViewBag.Model = data;
            return View();

        }




        [HttpGet]
        public IActionResult CpRegister()
        {
            List<SelectListItem> values = (from x in c.computers.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.Ram,

                                               Value = x.Pcid.ToString()
                                           }).ToList();
            ViewBag.v1 = values;

            List<SelectListItem> values2 = (from x in c.computers.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.Monitor,

                                               Value = x.Pcid.ToString()
                                           }).ToList();
            ViewBag.v2 = values2;

            return View();

            var data = c.computers.ToList();
            ViewBag.Model = data;
            return View();
           
        }



        [HttpPost]
        public IActionResult CpRegister(Computer cp)
        {

            computerReposi.Tadd(cp);
            return RedirectToAction("CpIndex");
        }
        public IActionResult CpDelete(int id)
        {
            computerReposi.TRemove(new Computer { Pcid = id });
            return RedirectToAction("CpIndex");
        }
    }
}

Deneme4/Views/Computer/CpIndex.cshtml
@using Deneme4.Models
@model List<Computer>

@{
    ViewData["Title"] = "CpIndex";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>CpIndex</h1>

<table class="table table-bordered">
    <tr>
        <th>Pcid</th>
        <th>Graphicscard</th>
        <th>Mainboard</th>
        <th>Ram</th>
        <th>Monitor</th>
    </tr>
    @foreach (var x in ViewBag.Model)
   {
        <tr>
           <td>@x.Pcid</td>
            <td>@x.Graphicscard</td>
            <td>@x.Mainboard</td>
            <td>@x.Ram</td>
            <td>@x.Monitor</td>
            <td><a href="/Computer/CpDelete/@x.Pcid" class="btn btn-danger">Delete</a>
            <td><a href="#" class="btn btn-success">Update</a>

        </tr>
    }
</table>
<a href="/Computer/CpRegister" class="btn btn-primary">Register</a>

    

Deneme4/Views/Computer/CpRegister.cshtml
@model Deneme4.Models.Computer
@{
    ViewData["Title"] = "CpRegister";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>


<h1>Computer Register Add Page</h1>
</br>

<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
    Click For Register
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Register</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                @using (Html.BeginForm("CpRegister", "Computer", FormMethod.Post))
                {

                    @Html.LabelFor(x => x.Graphicscard)
                    @Html.TextBoxFor(x => x.Graphicscard, new { @class = "form-control" })
                    @Html.LabelFor(x => x.Mainboard)
                    @Html.TextBoxFor(x => x.Mainboard, new { @class = "form-control" })
                    @Html.LabelFor(x => x.Ram)
                    @Html.TextBoxFor(x => x.Ram, new { @class = "form-control" })
                    @Html.LabelFor(x => x.Monitor)
                    @Html.TextBoxFor(x => x.Monitor, new { @class = "form-control" })
                    <button class="btn btn-info">Register</button>

                }

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button> 
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>

Deneme4/Views/Computer/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>